### ISSUE TITLE
load fail

### ISSUE THREAD

**Issue by davephillips** [gbrandt1/southpole-vcvrack#1]
Fedora 23 Linux
Rack 0.5.x

Built from latest git pull. No problems with the build, btw. However:

[warning] Failed to load library ./plugins/southpole-vcvrack/plugin.so: ./plugins/southpole-vcvrack/plugin.so: undefined symbol: _ZN6braids20ws_violent_overdriveE

Warnings like that typically indicate that an object didn't get compiled and/or linked. Please advise if you've a suggested fix. Very excited to try your modules ! :)

**Comment by gbrandt1** [comment]
Hi Dave,
Thanks, didn't see this on Mac and don't have a (private) Linux setup right now. according to grep on the firmware that symbol might become available by adding
SOURCES += parasites/braids/resources.cc
to the Makefile.

**Comment by davephillips** [comment]
Hey, thanks for the quick reply ! I followed your suggestion, it led to a series of missing symbols, all of which I've now resolved by grepping the sources and adding the relevant lines to the Makefile. I've attached my edited Makefile, you can diff for the additions. Also thought you might like this:
![southpolemodules](https://user-images.githubusercontent.com/7815938/35229898-9439c4f4-ff62-11e7-85c4-fe991cc7ea8c.png)
[Makefile.txt](https://github.com/gbrandt1/southpole-vcvrack/files/1652583/Makefile.txt)
