### ISSUE TITLE
Gnome: extreme output levels

### ISSUE THREAD

**Issue by phdsg** [gbrandt1/southpole-vcvrack#10]
even at default settings this thing goes way out of bounds. notice the scale knob on the scope ...  

![gnome](https://user-images.githubusercontent.com/33329578/36072807-bb849a06-0f26-11e8-8df9-620255307dbb.gif)

**Comment by gbrandt1** [comment]
the original is also very loud and always needed an attenuator down the chain because of no built-in volume knob. 
i'll reconsider the internal gain staging and output levels in the next version.

**Comment by gbrandt1** [comment]
fixed in master if you would like to test

**Comment by phdsg** [comment]
much better.
