### ISSUE TITLE
0.53 don't appear on Mac 

### ISSUE THREAD

**Issue by nay-seven** [gbrandt1/southpole-vcvrack#11]
i've test to replace 0.5.2, it's ok, but i see nothing with the last release 0.5.3
I'm on Mac yosemite

**Comment by killiun** [comment]
same.

**Comment by phdsg** [comment]
can you post rack's log.txt or console output?

**Comment by nay-seven** [comment]
[warning] Failed to load library /Users/yanledean/Documents/Rack/plugins/Southpole/plugin.dylib: dlopen(/Users/yanledean/Documents/Rack/plugins/Southpole/plugin.dylib, 2): Symbol not found: __ZN10FuseWidgetC1Ev
  Referenced from: /Users/yanledean/Documents/Rack/plugins/Southpole/plugin.dylib
  Expected in: flat namespace
 in /Users/yanledean/Documents/Rack/plugins/Southpole/plugin.dylib

**Comment by phdsg** [comment]
indeed. getting the same error in my vm.
you can try this until @gbrandt1 fixes the release:
`4899a0472574238bef26f05e0b4848bb28f5d07c63502f612867fe23b8137edf  Southpole-0.5.3-mac.zip
`
[Southpole-0.5.3-mac.zip](https://github.com/gbrandt1/southpole-vcvrack/files/1753499/Southpole-0.5.3-mac.zip)

**Comment by gbrandt1** [comment]
i updated the binaries, please try again

**Comment by nay-seven** [comment]
It's Ok now ! good job
Thanks

**Comment by gbrandt1** [comment]
Très bien
