### ISSUE TITLE
0.5.3 - Tags

### ISSUE THREAD

**Issue by DomiKamu** [gbrandt1/southpole-vcvrack#12]
Hi again,

IMO you'll must to review many tags you've used for your modules. Try to limit as possible UTILITY_TAG usage if you can. For example, for all blank panels, replace **UTILITY_TAG** by **BLANK_TAG**

Concerned modules:
- Fall
- Aux
- Piste
- Sssh
- Snake
- Gnome
- all blank panels

Dominique Camus.
Into attached .zip file: **Southpole.cpp** (edited)
[Southpole.zip](https://github.com/gbrandt1/southpole-vcvrack/files/1754386/Southpole.zip)

**Comment by gbrandt1** [comment]
ah yes i have a bug in the slug names... i will fix that in the future. 
you can add it by hand for now, check the youtube video, it's configures as Two Drunks and RND1,RND2 are connected to Riemann P5/V and M3/V

**Comment by DomiKamu** [comment]
I don't have seen bug in SLUG names... I recommend to don't change them, because existing .vcv patch files will cause error when load (same for "internal" name listed just before menu title).

What platform are you using for development and compile?

When compiling on Win, they're a lot of "warnings", do you know about this?

**Comment by nay-seven** [comment]
i feel this answer was for me in another issue ;-)

**Comment by gbrandt1** [comment]
ah yes not sure how that answer ended up here - don't github on the smartphone i guess...

Dominique your changes are implemented but will go in the next release

**Comment by DomiKamu** [comment]
It would be excellent about updated tags, of course for next release along Rack 0.6 (they'll few added, for 0.6, now listed into **Rack/include/tags.hpp**)
@Nay of course you're right, but probably these warnings will disappear against 0.6, wait & see...
I close this issue. Cheers!
