### ISSUE TITLE
0.5.3 Mac binaries non functioning

### ISSUE THREAD

**Issue by n6smith** [gbrandt1/southpole-vcvrack#15]
There seems to be an issue with v0.5.3 of both Southpole and Southpole-parasites's Mac Binaries 0.5.2 binary installs fine without issue but the current binaries of 0.5.3 do not. If you delete 0.5.2 and install 0.5.3 Southpole, nothing appears in the plugin list. Not even an entry for Southpole at all. Deleting 0.5.3 and adding back 0.5.2 results in Southpole being accessible once more. Tested and found same issue on two different Macs here using Public Binary of 0.5.1 of Rack..

**Comment by gbrandt1** [comment]
hi, i cannot reproduce the problem over here, the Mac binaries work fine for me. i need some more information to fix this. which version of Mac OSX are you using? can you start from the command line so we can see the error message?

**Comment by n6smith** [comment]
Here are the relevant errors in the VCV Rack Log.txt.. Sorry Gerhard, I should have posted this up with my original report...

[info] Loaded plugin /Users/n6smith/Documents/Rack/plugins/SonusModular/plugin.dylib
[warning] Failed to load library /Users/n6smith/Documents/Rack/plugins/Southpole/plugin.dylib: dlopen(/Users/n6smith/Documents/Rack/plugins/Southpole/plugin.dylib, 2): Symbol not found: __ZN10FuseWidgetC1Ev
  Referenced from: /Users/n6smith/Documents/Rack/plugins/Southpole/plugin.dylib
  Expected in: flat namespace
 in /Users/n6smith/Documents/Rack/plugins/Southpole/plugin.dylib
[warning] Failed to load library /Users/n6smith/Documents/Rack/plugins/Southpole-parasites/plugin.dylib: dlopen(/Users/n6smith/Documents/Rack/plugins/Southpole-parasites/plugin.dylib, 2): Symbol not found: __ZN10FuseWidgetC1Ev
  Referenced from: /Users/n6smith/Documents/Rack/plugins/Southpole-parasites/plugin.dylib
  Expected in: flat namespace
 in /Users/n6smith/Documents/Rack/plugins/Southpole-parasites/plugin.dylib
[info] Loaded plugin /Users/n6smith/Documents/Rack/plugins/Stellare-Modular/plugin.dylib

This is under both MacOS 10.12.6 and 10.13.2 and are the current Mac Binaries I downloaded from your Github Releases page

**Comment by gbrandt1** [comment]
Interesting. If you check the closed issues this problem was reported previously and consequently fixed.

**Comment by n6smith** [comment]
That is interesting because I downloaded the binaries last night and thats when I had the issue. However, I just tried again downloading once more.. using the binaries posted in the Releases page and this time it worked without issue... Very strange indeed.. but both are now functioning correctly. Maybe I made an error and used an older set of downloads, prior to you fixing the issue somehow.. or there was a caching issue...with the older version?

Anyhow, problem resolved here :)

Cheers

Nigel

**Comment by n6smith** [comment]
Did you change the version number of the file when you fixed it? If not, that might be where part of the issue occurred from my perspective at least :)

**Comment by gbrandt1** [comment]
No it was kept at 0.5.3 but since it wasn't officially announced yet I figured it's ok to just change the binary. The link from the vcv plugins page just points to the GitHub release and once it's there I'll keep the binaries as-is and rather fix issues with the next release

**Comment by n6smith** [comment]
Yeah.. Makes sense..  Thanks Gerhard..

**Comment by gbrandt1** [comment]
looking forward to your creations ;-)
