### ISSUE TITLE
0.5.3 Snake: buss assignment not written to patches

### ISSUE THREAD

**Issue by sbcook0** [gbrandt1/southpole-vcvrack#18]
OS: Win10
Rack: 5.1

Simple test:
1) Create a patch using 2 Snake Modules assign one module a buss other than 0
2) Save patch
3) Open patch

Expected result: the buss assignment should be preserved in the patch
Actual result: both modules are set to buss 0

Looking at the saved patch - the buss assignments are not written into Snake parameters.

This makes it difficult to use buss assignments as they have to be added back to the patch every time.

**Comment by gbrandt1** [comment]
thanks, yes, i've been slacking in implementing the persistency functions. 
added to the to-do list for the next version.

**Comment by gbrandt1** [comment]
part of 0.5.4, let me know if it works for you. thanks

**Comment by sbcook0** [comment]
Yes, snake settings are persistent now. It took a bit to get the patch running because Cornrows was renamed. Adding the new version was crashing the patch but I eventually got the patch rebuilt with 0.5.4 southpole and southpole-parasites. All good now, thanks.
