### ISSUE TITLE
CornrowsX segfaults Rack 0.6.x

### ISSUE THREAD

**Issue by davephillips** [gbrandt1/southpole-vcvrack#21]
Fedora 23 Linux
Rack master (0.6.x dev)

Greetings ! I'm testing your 0.6 branch and have run into one problem so far. As the subject line says, when I load CornrowsX it segfaults Rack every time. I ran make debug on Rack and have pasted the backtrace output to pastebin at https://pastebin.com/y6T3tK3h. I hope that helps, please advise if there's anything else you'd like me to try.

**Comment by phdsg** [comment]
why not post here: #19 ?

**Comment by davephillips** [comment]
@phdsg Ah, sorry about that, I'll follow up in that thread.
