### ISSUE TITLE
Don't find some modules

### ISSUE THREAD

**Issue by nay-seven** [gbrandt1/southpole-vcvrack#25]
Hello, i can 't find some last modules in my southpole or southpole parasites folder , example with ritardo ?
Can you help ? ;-)

**Comment by nay-seven** [comment]
One thing to complete my post, i realize i've the ritardo .svg ( as bandana,camilla...) in my res folder...Strange ?
for info i'm on Mac, rack 0.6 updated

**Comment by gbrandt1** [comment]
hi, you have to select the modes / new skins in the context menu. the README describes which module has which modes.

**Comment by nay-seven** [comment]
ok, right click to change feature (and skin) , solved ;-)
