### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by phdsg** [gbrandt1/southpole-vcvrack#3]
OS: win7 (mingw64)
Rack: 0.5
Plugin: master

i'm interested in your plugins. unfortunately they don't build here.

console output:  

> In file included from src/Sns.cpp:7:0:
src/Bjorklund.hpp: In member function 'void Bjorklund::iter()':
src/Bjorklund.hpp:58:9: error: 'reverse' was not declared in this scope
         reverse(sequence.begin(), sequence.end());
         ^~~~~~~
src/Bjorklund.hpp:66:18: error: 'rotate' is not a member of 'std'
             std::rotate(sequence.begin(), sequence.begin() + zeroCount, sequence.end());
                  ^~~~~~
src/Bjorklund.hpp:66:18: note: suggested alternative: '_S_ate'
             std::rotate(sequence.begin(), sequence.begin() + zeroCount, sequence.end());
                  ^~~~~~
                  _S_ate
In file included from src/Sns.cpp:7:0:
src/Bjorklund.hpp: In member function 'void Bjorklund::rotater(int)':
src/Bjorklund.hpp:89:18: error: 'rotate' is not a member of 'std'
             std::rotate(sequence.rbegin(),sequence.rbegin() + 1,sequence.rend());
                  ^~~~~~
src/Bjorklund.hpp:89:18: note: suggested alternative: '_S_ate'
             std::rotate(sequence.rbegin(),sequence.rbegin() + 1,sequence.rend());
                  ^~~~~~
                  _S_ate
src/Sns.cpp: At global scope:
src/Sns.cpp:64:2: error: 'uint' does not name a type; did you mean 'rint'?
  uint par_k = 1; // fill
  ^~~~
  rint
src/Sns.cpp:65:2: error: 'uint' does not name a type; did you mean 'rint'?
  uint par_l = 1; // pattern length
  ^~~~
  rint
src/Sns.cpp:66:2: error: 'uint' does not name a type; did you mean 'rint'?
  uint par_s = 1; // shift
  ^~~~
  rint
src/Sns.cpp:67:2: error: 'uint' does not name a type; did you mean 'rint'?
  uint par_a = 1; // accent
  ^~~~
  rint
src/Sns.cpp:68:2: error: 'uint' does not name a type; did you mean 'rint'?
  uint par_last;
  ^~~~
  rint
src/Sns.cpp:75:2: error: 'uint' does not name a type; did you mean 'rint'?
  uint currentStep = 0;
  ^~~~
  rint
src/Sns.cpp: In member function 'virtual void Sns::reset()':
src/Sns.cpp:81:14: error: 'par_l' was not declared in this scope
  euclid.init(par_l,par_k);
              ^~~~~
src/Sns.cpp:81:14: note: suggested alternative: 'params'
  euclid.init(par_l,par_k);
              ^~~~~
              params
src/Sns.cpp:81:20: error: 'par_k' was not declared in this scope
  euclid.init(par_l,par_k);
                    ^~~~~
src/Sns.cpp:81:20: note: suggested alternative: 'params'
  euclid.init(par_l,par_k);
                    ^~~~~
                    params
src/Sns.cpp:83:17: error: 'par_s' was not declared in this scope
  euclid.rotater(par_s);
                 ^~~~~
src/Sns.cpp:83:17: note: suggested alternative: 'params'
  euclid.rotater(par_s);
                 ^~~~~
                 params
src/Sns.cpp:87:6: error: 'par_a' was not declared in this scope
  if (par_a>0) {
      ^~~~~
src/Sns.cpp:87:6: note: suggested alternative: 'params'
  if (par_a>0) {
      ^~~~~
      params
src/Sns.cpp:96:10: error: 'par_a' was not declared in this scope
      if (par_a && euclid.sequence.at(i)) {
          ^~~~~
src/Sns.cpp:96:10: note: suggested alternative: 'params'
      if (par_a && euclid.sequence.at(i)) {
          ^~~~~
          params
src/Sns.cpp: In member function 'virtual void Sns::step()':
src/Sns.cpp:139:4: error: 'currentStep' was not declared in this scope
    currentStep = par_l;
    ^~~~~~~~~~~
src/Sns.cpp:139:4: note: suggested alternative: 'nextStep'
    currentStep = par_l;
    ^~~~~~~~~~~
    nextStep
src/Sns.cpp:139:18: error: 'par_l' was not declared in this scope
    currentStep = par_l;
                  ^~~~~
src/Sns.cpp:139:18: note: suggested alternative: 'params'
    currentStep = par_l;
                  ^~~~~
                  params
src/Sns.cpp:146:3: error: 'currentStep' was not declared in this scope
   currentStep++;
   ^~~~~~~~~~~
src/Sns.cpp:146:3: note: suggested alternative: 'nextStep'
   currentStep++;
   ^~~~~~~~~~~
   nextStep
src/Sns.cpp:147:22: error: 'par_l' was not declared in this scope
   if (currentStep >= par_l) {
                      ^~~~~
src/Sns.cpp:147:22: note: suggested alternative: 'params'
   if (currentStep >= par_l) {
                      ^~~~~
                      params
src/Sns.cpp:169:2: error: 'par_l' was not declared in this scope
  par_l = uint( 1. +       15.  * ( clampf( params[L_PARAM].value + inputs[L_INPUT].normalize(0.) / 9., 0.0f, 1.0f)));
  ^~~~~
src/Sns.cpp:169:2: note: suggested alternative: 'params'
  par_l = uint( 1. +       15.  * ( clampf( params[L_PARAM].value + inputs[L_INPUT].normalize(0.) / 9., 0.0f, 1.0f)));
  ^~~~~
  params
src/Sns.cpp:169:10: error: 'uint' was not declared in this scope
  par_l = uint( 1. +       15.  * ( clampf( params[L_PARAM].value + inputs[L_INPUT].normalize(0.) / 9., 0.0f, 1.0f)));
          ^~~~
src/Sns.cpp:169:10: note: suggested alternative: 'rint'
  par_l = uint( 1. +       15.  * ( clampf( params[L_PARAM].value + inputs[L_INPUT].normalize(0.) / 9., 0.0f, 1.0f)));
          ^~~~
          rint
src/Sns.cpp:170:2: error: 'par_s' was not declared in this scope
  par_s = uint(      (par_l-1.) * ( clampf( params[S_PARAM].value + inputs[S_INPUT].normalize(0.) / 9., 0.0f, 1.0f)));
  ^~~~~
src/Sns.cpp:170:2: note: suggested alternative: 'params'
  par_s = uint(      (par_l-1.) * ( clampf( params[S_PARAM].value + inputs[S_INPUT].normalize(0.) / 9., 0.0f, 1.0f)));
  ^~~~~
  params
src/Sns.cpp:171:2: error: 'par_k' was not declared in this scope
  par_k = uint( 1. + (par_l-1.) * ( clampf( params[K_PARAM].value + inputs[K_INPUT].normalize(0.) / 9., 0.0f, 1.0f)));
  ^~~~~
src/Sns.cpp:171:2: note: suggested alternative: 'params'
  par_k = uint( 1. + (par_l-1.) * ( clampf( params[K_PARAM].value + inputs[K_INPUT].normalize(0.) / 9., 0.0f, 1.0f)));
  ^~~~~
  params
src/Sns.cpp:172:2: error: 'par_a' was not declared in this scope
  par_a = float( par_k ) * ( clampf( params[ACCENT_PARAM].value + inputs[ACCENT_INPUT].normalize(0.) / 9., 0.0f, 1.0f));
  ^~~~~
src/Sns.cpp:172:2: note: suggested alternative: 'params'
  par_a = float( par_k ) * ( clampf( params[ACCENT_PARAM].value + inputs[ACCENT_INPUT].normalize(0.) / 9., 0.0f, 1.0f));
  ^~~~~
  params
src/Sns.cpp:180:33: error: 'par_last' was not declared in this scope
  if (par_l+par_s+par_a+par_k != par_last) {
                                 ^~~~~~~~
src/Sns.cpp:180:33: note: suggested alternative: 'va_list'
  if (par_l+par_s+par_a+par_k != par_last) {
                                 ^~~~~~~~
                                 va_list
src/Sns.cpp: In member function 'void SnsDisplay::drawPolygon(NVGcontext*)':
src/Sns.cpp:219:26: error: 'struct Sns' has no member named 'par_l'; did you mean 'params'?
   unsigned len = module->par_l;
                          ^~~~~
                          params
src/Sns.cpp:229:22: error: 'struct Sns' has no member named 'currentStep'
    if ( i == module->currentStep  ) {
                      ^~~~~~~~~~~
src/Sns.cpp:240:8: error: 'uint' was not declared in this scope
   for (uint i = 0; i < module->par_l; i++) {
        ^~~~
src/Sns.cpp:240:8: note: suggested alternative: 'rint'
   for (uint i = 0; i < module->par_l; i++) {
        ^~~~
        rint
src/Sns.cpp:240:20: error: 'i' was not declared in this scope
   for (uint i = 0; i < module->par_l; i++) {
                    ^
src/Sns.cpp:240:32: error: 'struct Sns' has no member named 'par_l'; did you mean 'params'?
   for (uint i = 0; i < module->par_l; i++) {
                                ^~~~~
                                params
src/Sns.cpp:241:30: error: 'struct Sns' has no member named 'par_l'; did you mean 'params'?
    float a = i/float(module->par_l);
                              ^~~~~
                              params
src/Sns.cpp:251:17: error: 'struct Sns' has no member named 'par_k'; did you mean 'params'?
     if (module->par_k == 1) nvgCircle(vg, x, y, 3.);
                 ^~~~~
                 params
src/Sns.cpp: In member function 'virtual void SnsDisplay::draw(NVGcontext*)':
src/Sns.cpp:284:50: error: 'struct Sns' has no member named 'par_k'; did you mean 'params'?
   snprintf(str,sizeof(str),"%2d %2d",int(module->par_k),int(module->par_l));
                                                  ^~~~~
                                                  params
src/Sns.cpp:284:69: error: 'struct Sns' has no member named 'par_l'; did you mean 'params'?
   snprintf(str,sizeof(str),"%2d %2d",int(module->par_k),int(module->par_l));
                                                                     ^~~~~
                                                                     params
src/Sns.cpp:287:50: error: 'struct Sns' has no member named 'par_s'; did you mean 'params'?
   snprintf(str,sizeof(str),"%2d %2d",int(module->par_s),int(module->par_a));
                                                  ^~~~~
                                                  params
src/Sns.cpp:287:69: error: 'struct Sns' has no member named 'par_a'; did you mean 'params'?
   snprintf(str,sizeof(str),"%2d %2d",int(module->par_s),int(module->par_a));
                                                                     ^~~~~
                                                                     params
src/Sns.cpp: In constructor 'SnsWidget::SnsWidget()':
src/Sns.cpp:313:52: error: 'y1' was not declared in this scope
  addParam(createParam<sp_SmallBlackKnob>(Vec(4   , y1   ), module, Sns::K_PARAM, 0., 1., .25));
                                                    ^~
src/Sns.cpp:315:57: error: 'yh' was not declared in this scope
  addParam(createParam<sp_SmallBlackKnob>(Vec(4   , y1+2*yh), module, Sns::S_PARAM, 0., 1., 0.));
                                                         ^~
make: *** [../../compile.mk:54: build/src/Sns.cpp.o] Error 1

**Comment by gbrandt1** [comment]
please be patient, there is no tag yet that is guaranteed to compile + work. 
i am still developing the initial version on multiple machines and in the master branch and just using the repo to move between machines 
i will make an announcement on fb once a tag has been made.

**Comment by phdsg** [comment]
i understand. no worries, just wanted to let u know...
i'm not on fb anymore, but i follow git activity and will try to build again from time to time :D
