### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by davephillips** [gbrandt1/southpole-vcvrack#4]
Fedora 23 Linux
Rack 0.5.x

Greetings ! Got some problems with the latest pull:

g++ -DTEST -DPARASITES -I./parasites -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -Wsuggest-override -std=c++11 -c -o build/src/Sns.cpp.o src/Sns.cpp
In file included from src/Sns.cpp:7:0:
src/Bjorklund.hpp: In member function ‘void Bjorklund::iter()’:
src/Bjorklund.hpp:58:49: error: ‘reverse’ was not declared in this scope
         reverse(sequence.begin(), sequence.end());
                                                 ^
src/Bjorklund.hpp:66:13: error: ‘rotate’ is not a member of ‘std’
             std::rotate(sequence.begin(), sequence.begin() + zeroCount, sequence.end());
             ^
src/Bjorklund.hpp: In member function ‘void Bjorklund::rotater(int)’:
src/Bjorklund.hpp:89:13: error: ‘rotate’ is not a member of ‘std’
             std::rotate(sequence.rbegin(),sequence.rbegin() + 1,sequence.rend());

Those problems seem to have been resolved by adding <algorithm> to the Bjorklund.hpp includes.

This problem has me stumped:

g++ -DTEST -DPARASITES -I./parasites -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -Wsuggest-override -std=c++11 -c -o build/src/Sns.cpp.o src/Sns.cpp
src/Sns.cpp: In constructor ‘SnsWidget::SnsWidget()’:
src/Sns.cpp:313:53: error: no matching function for call to ‘rack::Vec::Vec(int, double (&)(double) throw ())’
  addParam(createParam<sp_SmallBlackKnob>(Vec(4   , y1   ), module, Sns::K_PARAM, 0., 1., .25));
                                                     ^
In file included from ../../include/rack.hpp:4:0,
                 from src/Southpole.hpp:1,
                 from src/Sns.cpp:4:
../../include/math.hpp:160:2: note: candidate: rack::Vec::Vec(float, float)
  Vec(float x, float y) : x(x), y(y) {}
  ^
../../include/math.hpp:160:2: note:   no known conversion for argument 2 from ‘double(double) throw ()’ to ‘float’
../../include/math.hpp:159:2: note: candidate: rack::Vec::Vec()
  Vec() : x(0.0), y(0.0) {}
  ^
../../include/math.hpp:159:2: note:   candidate expects 0 arguments, 2 provided
../../include/math.hpp:156:8: note: candidate: constexpr rack::Vec::Vec(const rack::Vec&)
 struct Vec {
        ^
../../include/math.hpp:156:8: note:   candidate expects 1 argument, 2 provided
../../include/math.hpp:156:8: note: candidate: constexpr rack::Vec::Vec(rack::Vec&&)
../../include/math.hpp:156:8: note:   candidate expects 1 argument, 2 provided
src/Sns.cpp:314:55: error: no matching function for call to ‘rack::Vec::Vec(int, double (&)(double) throw ())’
  addParam(createParam<sp_SmallBlackKnob>(Vec(4+25, y1   ), module, Sns::L_PARAM, 0., 1., 1.));
                                                       ^
In file included from ../../include/rack.hpp:4:0,
                 from src/Southpole.hpp:1,
                 from src/Sns.cpp:4:
../../include/math.hpp:160:2: note: candidate: rack::Vec::Vec(float, float)
  Vec(float x, float y) : x(x), y(y) {}
  ^
../../include/math.hpp:160:2: note:   no known conversion for argument 2 from ‘double(double) throw ()’ to ‘float’
../../include/math.hpp:159:2: note: candidate: rack::Vec::Vec()
  Vec() : x(0.0), y(0.0) {}
  ^
../../include/math.hpp:159:2: note:   candidate expects 0 arguments, 2 provided
../../include/math.hpp:156:8: note: candidate: constexpr rack::Vec::Vec(const rack::Vec&)
 struct Vec {
        ^
../../include/math.hpp:156:8: note:   candidate expects 1 argument, 2 provided
../../include/math.hpp:156:8: note: candidate: constexpr rack::Vec::Vec(rack::Vec&&)
../../include/math.hpp:156:8: note:   candidate expects 1 argument, 2 provided
src/Sns.cpp:315:55: error: ‘yh’ was not declared in this scope
  addParam(createParam<sp_SmallBlackKnob>(Vec(4   , y1+2*yh), module, Sns::S_PARAM, 0., 1., 0.));
                                                       ^
../../compile.mk:53: recipe for target 'build/src/Sns.cpp.o' failed
make: *** [build/src/Sns.cpp.o] Error 1

Any suggestions ?

**Comment by gbrandt1** [comment]
yes: wait :-) ... sorry i'm developing on multiple machines and use the master branch to sync.
i'll tag something compilable and branch for development soon but right now i'm in a binge creating new modules so please be patient

**Comment by davephillips** [comment]
Not a problem. I always backup my working stuff, so I'm still good with the previous build. Patience is a virtue. :) Thanks for the reply, I'll look forward to your new work.
