### ISSUE TITLE
Southpole v1.0.0 fails to load in linux

### ISSUE THREAD

**Issue by therealkitman** [gbrandt1/southpole-vcvrack#48]
Hi, I read in  #36 that Southpole V1 was ready so I downloaded and installed the zip at https://github.com/gbrandt1/southpole-vcvrack/files/3745624/Southpole-1.0.0-lin.zip

However it fails to  load. Extract from log.txt says -

> [0.275 warn src/plugin.cpp:158] Could not load plugin /home/chris/.Rack/plugins-v1/Southpole: Failed to load library /home/chris/.Rack/plugins-v1/Southpole/plugin.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/chris/.Rack/plugins-v1/Southpole/plugin.so)

From a previous linux issue (and I may be misquoting slightly) but linux builds need to be compiled against glibc V2.23 not V2.27.

See https://community.vcvrack.com/t/rack-development-blog/5864/8

Thanks.

**Comment by netboy3** [comment]
I've built a build server running Ubuntu 16.04 which is the recommended version to build for Linux and have [re-built Southpole for Linux](https://github.com/gbrandt1/southpole-vcvrack/files/3747836/Southpole-1.0.0-lin.zip) there and re-posted on the OP. This version should run on most Linux versions, even not the latest ones. @therealkitman, thanks for bringing this to my attention. I'll be using this build server to build final plugins for Linux from now on.
As for Andrew's recommendation, it is really a hack and will fail in some cases. It will be great if you can try the new version and let me know if it works.

**Comment by therealkitman** [comment]
Hi @netboy3,
The re-built package now loads Southpole into my linux. Thank you very much!!!!!!!! :+1: 
It's nice to have them back in Rack and I'll start playing with them this week.
Regards...
