### ISSUE TITLE
Build fail on Windows

### ISSUE THREAD

**Issue by synthdude** [gbrandt1/southpole-vcvrack#5]
OS: win10 (mingw64)
Rack: 0.5
Plugin: master

Build fails on Mingw64 (Win 10):

[https://postimg.org/image/81vprhkod/](url)

I am no programmer, but will assist as much as I can.

**Comment by gbrandt1** [comment]
see issues below, please wait until i announce a tag. thanks

**Comment by synthdude** [comment]
Right, will close this for now.

**Comment by synthdude** [comment]
6c9ee40 compiled successfully on Win 10 now, thanks!
