### ISSUE TITLE
Smoke build on Mac?

### ISSUE THREAD

**Issue by bitfetcher** [gbrandt1/southpole-vcvrack#7]
Hey, I can't thank you enough for these modules!!

The latest "clone" to Mac (VCV 0.5.1, High Sierra, Xcode 9.2) fails to build the parasites version of Smoke.

 After making the "straight" version successfully, and then "make clean" the build goes as:

> make -f Makefile.parasites dist
> c++ -DTEST -DPARASITES -I./parasites -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7  -std=c++11 -stdlib=libc++ -c -o build/src/Southpole.cpp.o src/Southpole.cpp
> c++ -DTEST -DPARASITES -I./parasites -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7  -std=c++11 -stdlib=libc++ -c -o build/parasites/stmlib/utils/random.cc.o parasites/stmlib/utils/random.cc
> c++ -DTEST -DPARASITES -I./parasites -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7  -std=c++11 -stdlib=libc++ -c -o build/parasites/stmlib/dsp/units.cc.o parasites/stmlib/dsp/units.cc
> c++ -DTEST -DPARASITES -I./parasites -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7  -std=c++11 -stdlib=libc++ -c -o build/parasites/stmlib/dsp/atan.cc.o parasites/stmlib/dsp/atan.cc
> c++ -DTEST -DPARASITES -I./parasites -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7  -std=c++11 -stdlib=libc++ -c -o build/src/Smoke.cpp.o src/Smoke.cpp
> In file included from src/Smoke.cpp:13:
> In file included from ./parasites/clouds/dsp/granular_processor.h:45:
> In file included from ./parasites/clouds/dsp/pvoc/phase_vocoder.h:34:
> ./parasites/stmlib/fft/shy_fft.h:91:31: warning: all paths through this function will call itself [-Winfinite-recursion]
>   inline double cos(double x) { return cos(x); }
>                               ^
> ./parasites/stmlib/fft/shy_fft.h:92:31: warning: all paths through this function will call itself [-Winfinite-recursion]
>   inline double sin(double x) { return sin(x); }
>                               ^
> src/Smoke.cpp:310:9: error: cannot use arrow operator on a type
>           Panel->setBackground(SVG::load(assetPlugin(plugin, "res/Smoke6HP.svg")));
>                ^
> src/Smoke.cpp:311:9: error: cannot use arrow operator on a type
>           Panel->box.size = box.size;
>                ^
> 2 warnings and 2 errors generated.
> make: *** [build/src/Smoke.cpp.o] Error 1

I'm afraid I skipped C++ in my programming language path, but let me know if I can help (If this IS a bug).

Thanks again!

**Comment by bitfetcher** [comment]
Crap... never mind! I see the notes, and with Humo as the non-parasites version, I'm all good!

How do I delete this (non)issue?? ...

**Comment by gbrandt1** [comment]
just close it, button below :-) 
Smoke / parasites will be back soon
