### ISSUE TITLE
Feature request: Snake -> Medusa?

### ISSUE THREAD

**Issue by bitfetcher** [gbrandt1/southpole-vcvrack#9]
Hey, really loving these modules! Unfortch, C++ is not in my arsenal of languages, so I can't appreciate the ease/difficulty of this request, but could you, for example, sacrifice the bottom two (or four) jacks for a "Bus select" widget allowing for multiple instances of the Snake to pair up with its own groups of "children"? Thus all Snakes set to the same bus work together, but apart from those on other busses. 

The UI could be as simple (?) as a fixed-detente knob for say 8 busses, or a bank/bus pair of such knobs expanding the potential number, or a knob + LED display of the selected bus. 

I can imagine it might be tricky to handle changing the internal connections when the bus knob gets changed, so I leave all this for your consideration.

Many thanks for the fine plugins!

**Comment by gbrandt1** [comment]
Hi, yes this came to my mind also, and it was already discussed in the fb users group. i'll come up with something, probably a display at the top and + / - buttons to select the buss id. not sure yet if it will be a new module or a revision of Snake. cheers!
